name: artemis
version: 7.0.0-beta.4

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # safe to leave without nullsafety support
  # https://github.com/dart-lang/build/issues/3061#issuecomment-809413319
  build_config: ^0.4.7

  # partialy safe to leave without nullsafety support
  # https://github.com/dart-lang/code_builder/issues/303#issuecomment-791885756
  code_builder: ^3.7.0

  build: ^2.0.0
  collection: ^1.15.0
  dart_style: ^2.0.0
  equatable: ^2.0.0
  glob: ^2.0.1
  gql_code_builder: ^0.2.0-nullsafety.0
  gql_dedupe_link: ^2.0.0-nullsafety.1
  gql_exec: ^0.3.0-nullsafety.2
  gql_http_link: ^0.4.0-nullsafety.1
  gql_link: ^0.4.0-nullsafety.3
  gql: ^0.13.0-nullsafety.1
  http: ^0.13.1
  json_annotation: ^4.0.1
  meta: ^1.3.0
  path: ^1.8.0
  recase: ^4.0.0-nullsafety.0
  source_gen: ^1.0.0
  yaml: ^3.1.0

dev_dependencies:
  args: ^2.0.0
  build_runner: ^1.12.2
  build_test: ^2.0.0
  json_serializable: ^4.1.0
  build_resolvers: ^2.0.0
  pedantic: ^1.11.0
  test: ^1.16.8
  logging: ^1.0.1

