name: artemis
version: 1.0.4

authors:
  - Igor Borges <igor@borges.dev>

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^0.38.2
  build: ^1.1.4
  build_config: ^0.4.0
  source_gen: ^0.9.4+2
  path: ^1.6.2
  gql: ^0.2.0
  equatable: ^0.5.1
  recase: ^2.0.1
  glob: ^1.1.7
  code_builder: ^3.2.0
  http: ^0.12.0+2

dev_dependencies:
  args: ^1.5.2
  build_runner: ^1.5.0
  json_serializable: ^3.0.0
  test: ^1.6.3
  build_test: ^0.10.7+3
  pedantic: ^1.8.0+1
