name: artemis
version: 7.0.0-beta.2

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  build_config: ^0.4.5
  build: ^1.6.0
  code_builder: ^3.5.0
  collection: ^1.14.13
  dart_style: ^1.3.10
  equatable: ^2.0.0
  glob: ^1.2.0
  gql_code_gen: ^0.1.5
  gql_dedupe_link: ^1.0.10
  gql_exec: ^0.2.5
  gql_http_link: ^0.3.2
  gql_link: ^0.3.1-alpha
  gql: ^0.12.4
  http: ^0.12.2
  json_annotation: ^4.0.0
  meta: ^1.2.4
  path: ^1.7.0
  recase: ^3.0.1
  source_gen: ^0.9.10+1
  yaml: ^2.2.1

dev_dependencies:
  args: ^1.6.0
  build_runner: ^1.10.11
  build_test: ^1.3.2
  json_serializable: ^4.0.2
  build_resolvers: ^1.5.1
  pedantic: ^1.9.2
  test: ^1.15.7
  logging: ^0.11.4
