name: artemis
version: 7.3.2-beta

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build_config: ^1.0.0
  code_builder: ^4.1.0
  build: ^2.2.1
  collection: ^1.15.0
  dart_style: ^2.2.0
  equatable: ^2.0.3
  glob: ^2.0.2
  gql_code_builder: ^0.5.1-alpha
  gql_dedupe_link: ^2.0.3-alpha
  gql_exec: ^0.4.1-alpha
  gql_http_link: ^0.4.3-alpha
  gql_link: ^0.4.3-alpha
  gql: ^0.13.1-alpha
  http: ^0.13.4
  json_annotation: ^4.4.0
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.2.1
  yaml: ^3.1.0

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.8
  build_test: ^2.1.5
  json_serializable: ^6.1.5
  build_resolvers: ^2.0.6
  test: ^1.20.2
  logging: ^1.0.2
  lints: ^1.0.1
