name: artemis
version: 6.8.1-beta.1

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  build_config: ^0.4.2
  build: ^1.3.0
  code_builder: ^3.3.0
  collection: ^1.14.12
  dart_style: ^1.3.6
  equatable: ^1.2.0
  glob: ^1.2.0
  gql_code_gen: ^0.1.5
  gql_dedupe_link: ^1.0.10
  gql_exec: ^0.2.4
  gql_http_link: ^0.2.9
  gql_link: ^0.3.1-alpha
  gql: ^0.12.3
  http: ^0.12.1
  json_annotation: ^3.0.1
  meta: ^1.1.8
  path: ^1.6.4
  recase: ^3.0.0
  source_gen: ^0.9.5
  yaml: ^2.2.1

dev_dependencies:
  args: ^1.6.0
  build_runner: ^1.10.0
  build_test: ^1.2.0
  json_serializable: ^3.3.0
  pedantic: ^1.9.0
  test: ^1.14.6
  logging: ^0.11.4
