name: artemis
version: 7.0.0

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build_config: ^0.4.6
  build: ^1.6.3
  gql_code_gen: ^0.2.0-alpha.1
  gql_dedupe_link: ^2.0.0-nullsafety.1
  gql_exec: ^0.3.0-nullsafety.1
  gql_http_link: ^0.4.0-nullsafety.1
  gql_link: ^0.4.0-nullsafety.1
  gql: ^0.13.0-nullsafety.1
  code_builder: ^3.6.0
  collection: ^1.15.0
  dart_style: ^1.3.14
  equatable: ^2.0.0
  glob: ^2.0.0
  http: ^0.13.0
  json_annotation: ^4.0.0
  meta: ^1.3.0
  path: ^1.8.0
  recase: ^4.0.0-nullsafety.0
  source_gen: ^0.9.10+3
  yaml: ^3.1.0

dev_dependencies:
  args: ^2.0.0
  build_runner: ^1.11.5
  build_test: ^1.3.7
  json_serializable: ^4.0.2
  build_resolvers: ^1.5.4
  pedantic: ^1.11.0
  test: ^1.16.5
  logging: ^1.0.0

dependency_overrides:
  gql: ^0.13.0-nullsafety.1
  glob: ^2.0.0
#  gql:
#    path: /Users/Shared/workspace/pub.dev/gql/gql/