name: artemis
version: 7.0.0-beta.8

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build_config: ^1.0.0
  code_builder: ^4.0.0
  build: ^2.0.1
  collection: ^1.15.0
  dart_style: ^2.0.1
  equatable: ^2.0.0
  glob: ^2.0.1
  # temp release until gql team will not update their package
  gql_code_builder_temp: ^0.2.0-nullsafety.1
  gql_dedupe_link: ^2.0.0-nullsafety.1
  gql_exec: ^0.3.0-nullsafety.2
  gql_http_link: ^0.4.0-nullsafety.1
  gql_link: ^0.4.0-nullsafety.3
  gql: ^0.13.0-nullsafety.2
  http: ^0.13.2
  json_annotation: ^4.0.1
  meta: ^1.3.0
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.0.0
  yaml: ^3.1.0

dev_dependencies:
  args: ^2.1.0
  build_runner: ^2.0.1
  build_test: ^2.1.0
  json_serializable: ^4.1.1
  build_resolvers: ^2.0.1
  pedantic: ^1.11.0
  test: ^1.17.3
  logging: ^1.0.1

