name: pokemon_example
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http:

dev_dependencies:
  test:
  build_runner:
  json_serializable:
  lints: ^1.0.1
  artemis:
    path: ../../.
