name: graphbrainz_example
version: 0.0.1

authors:
  - Igor Borges <igor@borges.me>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.13.1
  intl: ^0.17.0

dev_dependencies:
  test: ^1.16.8
  build_runner: ^2.0.4
  json_serializable: ^4.1.0
  artemis:
    path: ../../.
