name: hasura_example
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http:
  gql_websocket_link:

dev_dependencies:
  test:
  lints: ^1.0.1
  build_runner:
  json_serializable:
  artemis:
    path: ../../.
