on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - refs/tags/*

name: Test, and deploy to pub.dev if tagged

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@master
    - name: Run tests
      uses: comigor/actions/dart-test@master
      env:
        DTA_DISABLE_ANALYZER: "YES"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@master
      if: startsWith(github.ref, 'refs/tags')
    - name: Publish to pub.dev
      uses: comigor/actions/pub-publish@master
      env:
        PUB_ACCESS_TOKEN: ${{ secrets.PUB_ACCESS_TOKEN }}
        PUB_EXPIRATION: ${{ secrets.PUB_EXPIRATION }}
        PUB_REFRESH_TOKEN: ${{ secrets.PUB_REFRESH_TOKEN }}
      if: startsWith(github.ref, 'refs/tags')
